### ISSUE TITLE
for pyqt4

### ISSUE THREAD

**Issue by seghier** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#5]
hello can you add support for pyqt4

**Comment by Jorgen-VikingGod** [comment]
hi @seghier I'm not familiar with PyQt.
Feel free to make a python fork

**Comment by Jorgen-VikingGod** [comment]
Some update on here... I tried my DarkStyle on an pyQt4 based app and it looked terrible.
Maybe it is better to use a PyQt5 lib, because the Fusion style is the base of my DarkStyle.
Without Fusion, the elements are not that nice and the palette did not match!
Also I have to dgg into the DropShadow part for PyQt5.
Currently I'm too busy to work on this repo. But it is on my ToDo list, to have a python fork for this ;)

**Comment by Jorgen-VikingGod** [comment]
long time no change here...
But I have good news: yesterday I had some time to look into the PyQt4/5 implementation and I think I can do a port.
Maybe first I will split out the darktheme and do some local adjustments on palette and stylesheets.
On PyQt4 there is no Fusion Style, so the best base style for my darkstyle is "Plastique".
And there is no QProxyStyle on PyQt4, only on PyQt5; so I have to base on the Styles directly and overload some methods...

**Here are some points to do:**
1. create and modify Python based style classes:
   - [ ] create Python style class for PyQt4 (based on Plastique Style)
   - [ ] create Python style class for PyQt5 (based on Fusion Style)
   - [ ] modify and fine tune the palette of Plastique Style
   - [ ] modify and fine tune the stylesheets for Plastique Style
2. create and modify Python based frameless window class:
   - [ ] create window and ui wrapper
   - [ ] use correct style depending on Python version

**Comment by Jorgen-VikingGod** [comment]
seems like someone already did a port of my work:
https://github.com/gmarull/qtmodern
